name: EmojiCrafter
version: 1.0.0
main: com.starshootercity.emojicraft.EmojiCraft
description: Paper plugin adding emojis to the game
api-version: '1.20'
author: cometcake575

permissions:
  emojicrafter.default:
    default: true
    description: Permission to use emojis - enabled by default
  emojicrafter.admin:
    default: op
    description: Permission to reload emojis

commands:
  emojicrafter-reload:
    permission: emojicrafter.admin
    description: Reload emojis
    usage: /<command>
